// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// gen-notice.ts — regenerate scripts/nuget/NOTICE.txt from the vendored license
// set. Run with Node.js v24+ (TypeScript strip-types).
//
// NOTICE.txt aggregates every third-party copyright/license notice for the
// components redistributed in this repository and compiled into the shipped
// binaries (v8jsi.dll, v8jsisb.dll, sbox.dll, v8host.exe) or shipped as headers.
// It is AUTO-GENERATED by scanning deps/ for license files, so it cannot
// silently drift from the vendored set — re-run it after every fork-sync.
//
//   node scripts/gen-notice.ts           # regenerate scripts/nuget/NOTICE.txt
//   node scripts/gen-notice.ts --check   # verify it is current (CI gate); exit 1 on drift
//
// Note: this lists notices for vendored third-party code. The project's own
// license (MIT) ships separately as the package LICENSE, not here.

import { parseArgs } from "node:util";
import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

import { repoRoot } from "./build-common.ts";

const OUT = path.join(repoRoot, "scripts", "nuget", "NOTICE.txt");
const SEP = "-".repeat(78);

// The standard Microsoft third-party NOTICE prefix.
const HEADER = `NOTICES AND INFORMATION
Do Not Translate or Localize

This software incorporates material from third parties. Microsoft makes
certain open source code available at https://3rdpartysource.microsoft.com,
or you may send a check or money order for US $5.00, including the product
name, the open source component name, and version number, to:

Source Code Compliance Team
Microsoft Corporation
One Microsoft Way
Redmond, WA 98052
USA

Notwithstanding any other terms, you may reverse engineer this software to
the extent required to debug changes to any libraries licensed under the
GNU Lesser General Public License.
`;

// Third-party source we ship as HEADERS that has no vendored license file of
// its own (its upstream license text, reproduced here for attribution).
const INLINE: { component: string; text: string }[] = [
  {
    component: "facebook/hermes — JSI interface (src/jsi/jsi.{h,cpp}, jsi-inl.h, instrumentation.h)",
    text: `MIT License

Copyright (c) Facebook, Inc. and its affiliates.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`,
  },
];

// Roots scanned for license files (the vendored third-party trees).
const SCAN_ROOTS = ["deps/chromium", "deps/nodejs", "deps/asio", "deps/gn"];

// A filename is a license notice if it matches this and is not source/script.
const LICENSE_NAME = /^(LICENSE|LICENCE|COPYING|COPYRIGHT)([._-].*)?$/i;
const NOT_LICENSE_EXT = /\.(cc|cpp|cxx|h|hpp|js|ts|py|pm|sh|rs|go|in|cmake|gn|gni)$/i;

// List vendored files via git (tracked + new-but-not-ignored), so freshly added
// license files are picked up before they are committed.
function vendoredFiles(): string[] {
  const run = (cmd: string): string[] =>
    execSync(cmd, { cwd: repoRoot, encoding: "utf-8", maxBuffer: 256 * 1024 * 1024 })
      .split(/\r?\n/)
      .filter((l) => l.length > 0);
  const roots = SCAN_ROOTS.join(" ");
  const tracked = run(`git ls-files -- ${roots}`);
  let untracked: string[] = [];
  try {
    untracked = run(`git ls-files --others --exclude-standard -- ${roots}`);
  } catch {
    /* no untracked; fine */
  }
  return Array.from(new Set([...tracked, ...untracked]));
}

// Discover every license file under the scanned roots, sorted for a stable,
// diff-able output.
function discoverLicenseFiles(): string[] {
  return vendoredFiles()
    .filter((f) => {
      const base = path.basename(f);
      return LICENSE_NAME.test(base) && !NOT_LICENSE_EXT.test(base);
    })
    .sort((a, b) => a.localeCompare(b));
}

// Build the NOTICE.txt content from the header, the inline notices, and every
// discovered license file (verbatim).
function render(licenseFiles: string[]): string {
  const parts: string[] = [HEADER];
  for (const inl of INLINE) {
    parts.push(`${SEP}\n\nComponent: ${inl.component}\n\n${inl.text.trimEnd()}\n`);
  }
  for (const rel of licenseFiles) {
    const text = fs.readFileSync(path.join(repoRoot, rel), "utf-8").replace(/\r\n/g, "\n");
    const component = path.dirname(rel).replace(/\\/g, "/");
    parts.push(
      `${SEP}\n\nComponent: ${component}\nLicense file: ${rel.replace(/\\/g, "/")}\n\n${text.trimEnd()}\n`,
    );
  }
  return parts.join("\n");
}

function main(): void {
  const { values: args } = parseArgs({
    options: { check: { type: "boolean", default: false } },
    allowNegative: true,
  });

  const licenseFiles = discoverLicenseFiles();
  const content = render(licenseFiles);
  const count = INLINE.length + licenseFiles.length;

  if (args.check) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf-8").replace(/\r\n/g, "\n") : "";
    if (current.trimEnd() !== content.trimEnd()) {
      console.error(
        `NOTICE.txt is STALE. Re-run \`node scripts/gen-notice.ts\` and commit the result.\n` +
          `(scanned ${count} third-party notices)`,
      );
      process.exit(1);
    }
    console.log(`NOTICE.txt is up to date (${count} third-party notices).`);
    return;
  }

  fs.writeFileSync(OUT, content, "utf-8");
  console.log(`Wrote ${OUT} (${count} third-party notices from ${licenseFiles.length} license files).`);
}

main();
