// Generate src/version_info_gen.h from config.json for the **new**
// Microsoft.JavaScript.V8 package binaries (v8jsi.dll, v8jsisb.dll,
// mkv8snapshot.exe, sbox.dll, v8host.exe). It emits only the version NUMBERS;
// the shared + per-binary strings live in src/version_info.rc.
//
// The version comes from config.json.v8jsi_version (the Node.js-aligned 24.x
// scheme the new package ships on), NOT config.json.version (the legacy
// ReactNative.V8Jsi.Windows scheme). The legacy build keeps its own resource via
// src/version.rc + scripts/fetch_code.ps1 and is intentionally left untouched.
//
// Usage: node generate_version_info.ts [--config <path>] [--output <path>]

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { parseArgs } from "node:util";

const scriptDir = dirname(
  new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/i, "$1"),
);

const { values } = parseArgs({
  options: {
    config: { type: "string", default: join(scriptDir, "..", "config.json") },
    output: { type: "string", default: join(scriptDir, "version_info_gen.h") },
  },
});

const config = JSON.parse(readFileSync(values.config!, "utf8"));
const version = (config.v8jsi_version as string) ?? "0.0.0";
const [major = "0", minor = "0", build = "0"] = version.split(".");
const revision = "0";
const versionStr = `${major}.${minor}.${build}.${revision}`;

const header = `// Generated by src/generate_version_info.ts from config.json (v8jsi_version).
// DO NOT EDIT. Version numbers for the Microsoft.JavaScript.V8 package binaries;
// strings live in src/version_info.rc.
#ifndef V8JSI_VERSION_INFO_GEN_H
#define V8JSI_VERSION_INFO_GEN_H
#define VER_FILE_VERSION     ${major},${minor},${build},${revision}
#define VER_FILE_VERSION_STR "${versionStr}"
#endif  // V8JSI_VERSION_INFO_GEN_H
`;

writeFileSync(values.output!, header);
console.log(`Generated ${values.output} (version ${versionStr})`);
