name: v8jsi_0.0.$(Date:yyMM.d)$(Rev:rrr)

trigger:
- master
- "*-stable"

pr:
  - master
  - "*-stable"

pool:
  vmImage: 'windows-latest'

jobs:
  - job: V8JsiBuild
    timeoutInMinutes: 180
    displayName: Build the v8jsi.dll binary for supported architectures and flavors
    strategy:
      matrix:
        Desktop|x64|Debug:
          BuildConfiguration: Debug
          BuildPlatform: x64
          AppPlatform: win32
          RunUnitTests: true
          NuGetId: ReactNative.V8Jsi.Windows.nuspec
        Desktop|x86|Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
          AppPlatform: win32
          RunUnitTests: true
          NuGetId: ReactNative.V8Jsi.Windows.nuspec
        Desktop|ARM64|Debug:
          BuildConfiguration: Debug
          BuildPlatform: arm64
          AppPlatform: win32
          RunUnitTests: true
          NuGetId: ReactNative.V8Jsi.Windows.nuspec
        Desktop|x64|Release:
          BuildConfiguration: Release
          BuildPlatform: x64
          AppPlatform: win32
          RunUnitTests: true
          NuGetId: ReactNative.V8Jsi.Windows.nuspec
        Desktop|x86|Release:
          BuildConfiguration: Release
          BuildPlatform: x86
          AppPlatform: win32
          RunUnitTests: true
          NuGetId: ReactNative.V8Jsi.Windows.nuspec
        Desktop|ARM64|Release:
          BuildConfiguration: Release
          BuildPlatform: arm64
          AppPlatform: win32
          RunUnitTests: true
          NuGetId: ReactNative.V8Jsi.Windows.nuspec
        Universal|x64|Debug:
          BuildConfiguration: Debug
          BuildPlatform: x64
          AppPlatform: uwp
          RunUnitTests: false
          NuGetId: ReactNative.V8Jsi.Windows.UWP
        Universal|x86|Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
          AppPlatform: uwp
          RunUnitTests: false
          NuGetId: ReactNative.V8Jsi.Windows.UWP
        Universal|ARM64|Debug:
          BuildConfiguration: Debug
          BuildPlatform: arm64
          AppPlatform: uwp
          RunUnitTests: false
          NuGetId: ReactNative.V8Jsi.Windows.UWP
        Universal|x64|Release:
          BuildConfiguration: Release
          BuildPlatform: x64
          AppPlatform: uwp
          RunUnitTests: false
          NuGetId: ReactNative.V8Jsi.Windows.UWP
        Universal|x86|Release:
          BuildConfiguration: Release
          BuildPlatform: x86
          AppPlatform: uwp
          RunUnitTests: false
          NuGetId: ReactNative.V8Jsi.Windows.UWP
        Universal|ARM64|Release:
          BuildConfiguration: Release
          BuildPlatform: arm64
          AppPlatform: uwp
          RunUnitTests: false
          NuGetId: ReactNative.V8Jsi.Windows.UWP

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '2.x'
          addToPath: true
          architecture: 'x64'
      - template: .ado/build-dll.yml
        parameters:
          outputPath: $(Build.ArtifactStagingDirectory)
          appPlatform: $(AppPlatform)
          runUnitTests: $(RunUnitTests)

  - job: V8JsiPublishNuget
    dependsOn:
      - V8JsiBuild
    displayName: Publish Nuget
    steps:
      - checkout: none

      - task: NuGetToolInstaller@0
        inputs:
          versionSpec: ">=4.6.0"

      - task: DownloadBuildArtifacts@0
        displayName: Download Build outputs
        inputs:
          artifactName: V8Jsi
          downloadPath: $(System.DefaultWorkingDirectory)

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $config = Get-Content (Join-Path $(System.DefaultWorkingDirectory) "V8Jsi\config.json") | Out-String | ConvertFrom-Json
            $Version = $config.version
            Write-Host "##vso[task.setvariable variable=Version]$Version"

      - task: NuGetCommand@2
        displayName: 'NuGet Pack'
        inputs:
          command: pack
          packagesToPack: $(System.DefaultWorkingDirectory)\V8Jsi\ReactNative.V8Jsi.Windows.nuspec
          packDestination: $(System.DefaultWorkingDirectory)\NugetRootFinal
          buildProperties: Id=$(NuGetId);CommitId=$(Build.SourceVersion);nugetroot=$(System.DefaultWorkingDirectory)\V8Jsi;RepoUri=$(Build.Repository.Uri)
          versioningScheme: byEnvVar
          versionEnvVar: Version
          includeSymbols: true

      - task: PublishBuildArtifacts@1
        displayName: "Publish final nuget artifacts"
        inputs:
          PathtoPublish: $(System.DefaultWorkingDirectory)\NugetRootFinal
          ArtifactName: "V8Jsi-final-nuget"
