name: v8jsi_win_pr_0.0.$(Date:yyMM.d)$(Rev:rrr)

trigger: none
pr:
  branches:
    include:
      - master
      - "*-stable"
  paths:
    exclude:
      - android/*
      - .ado/android-*.yml
      - README.md
      - docs/*

pool:
  vmImage: 'windows-2019'

jobs:
  - template: windows-jobs.yml