name: v8jsi_pr_0.0.$(Date:yyMM.d)$(Rev:rrr)

trigger: none
pr:
  - master
  - "*-stable"

extends:
  template: windows-jobs.yml@self
  parameters:
    # PR builds must pass false.
    isPublish: false
    # It must be false for real builds. Use true only for the build pipeline debugging.
    fakeBuild: false
