name: v8jsi_ci_0.0.$(Date:yyMM.d)$(Rev:rrr)

# The triggers are overridden by the ADO pipeline definitions.
trigger: none
pr: none

variables:
  - group: V8-Jsi Secrets
  - name: ArtifactServices.Symbol.AccountName
    value: microsoft
  - name: ArtifactServices.Symbol.PAT
    value: $(pat-symbols-publish-microsoft)
  - name: tags
    value: production,externalfacing

extends:
  template: windows-jobs.yml@self
  parameters:
    # CI builds must pass true.
    isPublish: true
    # It must be false for real builds. Use true only for the build pipeline debugging.
    fakeBuild: false