name: v8jsi_win_pr_0.0.$(Date:yyMM.d)$(Rev:rrr)

trigger: none
pr:
  - master
  - "*-stable"

pool:
  name: rnw-pool-4
  demands: ImageOverride -equals rnw-img-vs2022

jobs:
  - template: windows-jobs.yml
