name: v8jsi_win_ci_0.0.$(Date:yyMM.d)$(Rev:rrr)

pr: none
trigger:
  branches:
    include:
      - master
      - "*-stable"
  paths:
    exclude:
      - README.md
      - docs/*

resources:
  repositories:
  - repository: OfficePipelineTemplates
    type: git
    name: 1ESPipelineTemplates/OfficePipelineTemplates
    ref: refs/tags/release

variables:
  - group: V8-Jsi Secrets
  - name: ArtifactServices.Symbol.AccountName
    value: microsoft
  - name: ArtifactServices.Symbol.PAT
    value: $(pat-symbols-publish-microsoft)
  - name: tags
    value: production,externalfacing

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: OE-OfficePublic
      demands:
        - ImageVersionOverride -equals 69.0.0

    sdl:
      baseline:
        baselineFile: $(Build.SourcesDirectory)\.ado\guardian\SDL\.gdnbaselines
      eslint:
        enableExclusions: true
        # This repo does not ship any javascript code. But has many test cases for the js engine that fail parsing, have code considered insecure and crash eslint.
        exclusionPatterns: |
          '**/*.[jt]s'
    stages:
    - stage: main
      jobs:
      - template: .ado/windows-jobs.yml@self
        parameters:
          isPublish: true
